import { useFormik } from 'formik';
import Head from 'next/head';
import { useRouter } from 'next/router';
import * as Yup from 'yup';
import { motion as m } from 'framer-motion';

export default function Home() {
	// Router
	const router = useRouter();

	// Formik Logics
	const formik = useFormik({
		initialValues: {
			name: '',
			email: '',
			country: '',
			terms: false,
		},

		// Validate form
		validationSchema: Yup.object({
			name: Yup.string().max(15, 'Name must be 15 characters or less.').required('Name is required'),
			email: Yup.string().email('Invalid email address.').required('Email is required'),
			country: Yup.string().required('Country is required.'),
			terms: Yup.boolean().oneOf([true], 'Terms of service must be checked.'),
		}),

		// Submit form
		onSubmit: (values) => {
			console.log('✅', values);

			router.push({ pathname: '/success', query: values });
		},
	});

	return (
		<m.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<main className="container mx-auto p-4 h-screen flex items-center justify-center ">
				<form onSubmit={formik.handleSubmit} className="bg-white rounded-lg lg:flex sm:w-4/5">
					<div className=" text-gray-700 p-10 lg:p-20 basis-2/3">
						<h1 className="text-2xl sm:text-3xl text-gray-500 pb-2">Lets get started 🚀</h1>
						<p className="sm:text-lg text-gray-500">
							Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati sit illo ex laborum amet quasi nihil
							sint dolore fugit ad.
						</p>
						<div className="mt-6">
							<div className="pb-4">
								<label
									htmlFor="name"
									id="name"
									className={`block text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`}
								>
									{formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
								</label>
								<input
									className="border-2 border-gray-500 p-2 rounded-md w-full focus:outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/50 focus:ring-offset-1 placeholder:text-sm  placeholder:text-gray-400 transition duration-150"
									type="text"
									name="name"
									placeholder="Enter Your Name"
									onChange={formik.handleChange}
									onBlur={formik.handleBlur}
								/>
							</div>
							<div className="pb-4">
								<label
									htmlFor="email"
									id="email"
									className={`block text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`}
								>
									{formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}
								</label>
								<input
									className="border-2 border-gray-500 p-2 rounded-md w-full focus:outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/50 focus:ring-offset-1 placeholder:text-sm  placeholder:text-gray-400 transition duration-150"
									type="email"
									name="email"
									placeholder="Enter Your Email"
									value={formik.values.email}
									onChange={formik.handleChange}
									onBlur={formik.handleBlur}
								/>
							</div>
							<div className="pb-4">
								<label
									htmlFor="country"
									id="country"
									className={`block text-sm pb-2 ${
										formik.touched.country && formik.errors.country ? 'text-red-400' : ''
									}`}
								>
									{formik.touched.country && formik.errors.country ? formik.errors.country : 'Country'}
								</label>
								<select
									name="country"
									id="country"
									className="border-2 border-gray-500 p-2 rounded-md w-full focus:outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/50 focus:ring-offset-1 transition duration-15"
									value={formik.values.country}
									onChange={formik.handleChange}
									onBlur={formik.handleBlur}
								>
									<option value="">--Select your country--</option>
									<option>United States</option>
									<option>United Kingdom</option>
									<option>Germany</option>
									<option>Norway</option>
								</select>
							</div>
							<div className="pb-4">
								<label
									htmlFor="terms"
									id="terms"
									className={`block text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`}
								>
									{formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms of service'}
								</label>
								<div className="flex gap-2 md:items-center">
									<input
										className="w-5 h-5 text-teal-500 border-2 border-gray-500 p-2 rounded-sm focus:outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/50 focus:ring-offset-1 transition duration-150"
										type="checkbox"
										name="terms"
										placeholder="Enter Your Email"
										value="checked"
										onChange={formik.handleChange}
										onBlur={formik.handleBlur}
									/>
									<p className="text-sm text-gray-500">
										I agree to the terms of service that my data will be taken and sold 😉
									</p>
								</div>
							</div>
							<button
								type="submit"
								className="bg-teal-500 text-base text-white rounded-lg w-full py-3 mt-6 hover:bg-teal-600 transition duration-150 focus:outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-500/50 focus:ring-offset-1"
							>
								Submit
							</button>
						</div>
					</div>
					<div className="relative basis-1/3">
						<img
							className="object-cover rounded-lg rounded-tl-none rounded-bl-none absolute w-full h-full"
							src="https://images.unsplash.com/photo-1547638375-ebf04735d792?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=1000&amp;q=80"
							alt="six assorted-color dice"
						/>
					</div>
				</form>
			</main>
		</m.div>
	);
}
